// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/banners_api.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// BannerType contains the set of possible banner types to display
type Banner_BannerType int32

const (
	Banner_Error   Banner_BannerType = 0
	Banner_Info    Banner_BannerType = 1
	Banner_Warning Banner_BannerType = 2
)

var Banner_BannerType_name = map[int32]string{
	0: "Error",
	1: "Info",
	2: "Warning",
}

var Banner_BannerType_value = map[string]int32{
	"Error":   0,
	"Info":    1,
	"Warning": 2,
}

func (x Banner_BannerType) String() string {
	return proto.EnumName(Banner_BannerType_name, int32(x))
}

func (Banner_BannerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_420fb4f4a183e532, []int{0, 0}
}

type Banner struct {
	//Immutable Id of the banner
	BannerId int32 `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	// The type of banner (Error, Info, or Warning)
	// This influences how the UI displays the banner
	BannerType Banner_BannerType `protobuf:"varint,2,opt,name=banner_type,json=bannerType,proto3,enum=github.go_sample_service.Banner_BannerType" json:"banner_type,omitempty"`
	// Date/time when the banner should no longer be presented to users. If not set
	// the banner does not automatically expire
	ExpiresAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Date/time when the banner was created in the system
	// This is internal metadata and not meant to be displayed in the UI
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Id of the GitHub repo which the banner is associated with
	RepoId int32 `protobuf:"varint,5,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	// Id of the GitHub user who created this banner
	// This is internal metadata and not meant to be displayed in the UI
	CreatorId int32 `protobuf:"varint,6,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	// The message contained in the banner
	// This should be displayed in the UI
	Message              string   `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Banner) Reset()         { *m = Banner{} }
func (m *Banner) String() string { return proto.CompactTextString(m) }
func (*Banner) ProtoMessage()    {}
func (*Banner) Descriptor() ([]byte, []int) {
	return fileDescriptor_420fb4f4a183e532, []int{0}
}

func (m *Banner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Banner.Unmarshal(m, b)
}
func (m *Banner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Banner.Marshal(b, m, deterministic)
}
func (m *Banner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Banner.Merge(m, src)
}
func (m *Banner) XXX_Size() int {
	return xxx_messageInfo_Banner.Size(m)
}
func (m *Banner) XXX_DiscardUnknown() {
	xxx_messageInfo_Banner.DiscardUnknown(m)
}

var xxx_messageInfo_Banner proto.InternalMessageInfo

func (m *Banner) GetBannerId() int32 {
	if m != nil {
		return m.BannerId
	}
	return 0
}

func (m *Banner) GetBannerType() Banner_BannerType {
	if m != nil {
		return m.BannerType
	}
	return Banner_Error
}

func (m *Banner) GetExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *Banner) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Banner) GetRepoId() int32 {
	if m != nil {
		return m.RepoId
	}
	return 0
}

func (m *Banner) GetCreatorId() int32 {
	if m != nil {
		return m.CreatorId
	}
	return 0
}

func (m *Banner) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddBannerRequest struct {
	// The banner to add
	Banner               *Banner  `protobuf:"bytes,1,opt,name=banner,proto3" json:"banner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBannerRequest) Reset()         { *m = AddBannerRequest{} }
func (m *AddBannerRequest) String() string { return proto.CompactTextString(m) }
func (*AddBannerRequest) ProtoMessage()    {}
func (*AddBannerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_420fb4f4a183e532, []int{1}
}

func (m *AddBannerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBannerRequest.Unmarshal(m, b)
}
func (m *AddBannerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBannerRequest.Marshal(b, m, deterministic)
}
func (m *AddBannerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBannerRequest.Merge(m, src)
}
func (m *AddBannerRequest) XXX_Size() int {
	return xxx_messageInfo_AddBannerRequest.Size(m)
}
func (m *AddBannerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBannerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBannerRequest proto.InternalMessageInfo

func (m *AddBannerRequest) GetBanner() *Banner {
	if m != nil {
		return m.Banner
	}
	return nil
}

type AddBannerResponse struct {
	// The banner that was added
	Banner               *Banner  `protobuf:"bytes,1,opt,name=banner,proto3" json:"banner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBannerResponse) Reset()         { *m = AddBannerResponse{} }
func (m *AddBannerResponse) String() string { return proto.CompactTextString(m) }
func (*AddBannerResponse) ProtoMessage()    {}
func (*AddBannerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_420fb4f4a183e532, []int{2}
}

func (m *AddBannerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBannerResponse.Unmarshal(m, b)
}
func (m *AddBannerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBannerResponse.Marshal(b, m, deterministic)
}
func (m *AddBannerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBannerResponse.Merge(m, src)
}
func (m *AddBannerResponse) XXX_Size() int {
	return xxx_messageInfo_AddBannerResponse.Size(m)
}
func (m *AddBannerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBannerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBannerResponse proto.InternalMessageInfo

func (m *AddBannerResponse) GetBanner() *Banner {
	if m != nil {
		return m.Banner
	}
	return nil
}

type DeleteBannerRequest struct {
	// The Id of the banner to delete
	BannerId             int32    `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBannerRequest) Reset()         { *m = DeleteBannerRequest{} }
func (m *DeleteBannerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBannerRequest) ProtoMessage()    {}
func (*DeleteBannerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_420fb4f4a183e532, []int{3}
}

func (m *DeleteBannerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBannerRequest.Unmarshal(m, b)
}
func (m *DeleteBannerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBannerRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBannerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBannerRequest.Merge(m, src)
}
func (m *DeleteBannerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBannerRequest.Size(m)
}
func (m *DeleteBannerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBannerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBannerRequest proto.InternalMessageInfo

func (m *DeleteBannerRequest) GetBannerId() int32 {
	if m != nil {
		return m.BannerId
	}
	return 0
}

type DeleteBannerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBannerResponse) Reset()         { *m = DeleteBannerResponse{} }
func (m *DeleteBannerResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBannerResponse) ProtoMessage()    {}
func (*DeleteBannerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_420fb4f4a183e532, []int{4}
}

func (m *DeleteBannerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBannerResponse.Unmarshal(m, b)
}
func (m *DeleteBannerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBannerResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBannerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBannerResponse.Merge(m, src)
}
func (m *DeleteBannerResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBannerResponse.Size(m)
}
func (m *DeleteBannerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBannerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBannerResponse proto.InternalMessageInfo

type UpdateBannerRequest struct {
	// The Id of the banner to update
	BannerId int32 `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	// Date/time when the banner should no longer be presented to users. If not set
	// the banner does not automatically expire
	ExpiresAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// The message contained in the banner
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBannerRequest) Reset()         { *m = UpdateBannerRequest{} }
func (m *UpdateBannerRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBannerRequest) ProtoMessage()    {}
func (*UpdateBannerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_420fb4f4a183e532, []int{5}
}

func (m *UpdateBannerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBannerRequest.Unmarshal(m, b)
}
func (m *UpdateBannerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBannerRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBannerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBannerRequest.Merge(m, src)
}
func (m *UpdateBannerRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBannerRequest.Size(m)
}
func (m *UpdateBannerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBannerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBannerRequest proto.InternalMessageInfo

func (m *UpdateBannerRequest) GetBannerId() int32 {
	if m != nil {
		return m.BannerId
	}
	return 0
}

func (m *UpdateBannerRequest) GetExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *UpdateBannerRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateBannerResponse struct {
	// The updated banner
	Banner               *Banner  `protobuf:"bytes,1,opt,name=banner,proto3" json:"banner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBannerResponse) Reset()         { *m = UpdateBannerResponse{} }
func (m *UpdateBannerResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBannerResponse) ProtoMessage()    {}
func (*UpdateBannerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_420fb4f4a183e532, []int{6}
}

func (m *UpdateBannerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBannerResponse.Unmarshal(m, b)
}
func (m *UpdateBannerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBannerResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBannerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBannerResponse.Merge(m, src)
}
func (m *UpdateBannerResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBannerResponse.Size(m)
}
func (m *UpdateBannerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBannerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBannerResponse proto.InternalMessageInfo

func (m *UpdateBannerResponse) GetBanner() *Banner {
	if m != nil {
		return m.Banner
	}
	return nil
}

type GetBannerRequest struct {
	// The Id of the banner to retrieve
	BannerId             int32    `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBannerRequest) Reset()         { *m = GetBannerRequest{} }
func (m *GetBannerRequest) String() string { return proto.CompactTextString(m) }
func (*GetBannerRequest) ProtoMessage()    {}
func (*GetBannerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_420fb4f4a183e532, []int{7}
}

func (m *GetBannerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBannerRequest.Unmarshal(m, b)
}
func (m *GetBannerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBannerRequest.Marshal(b, m, deterministic)
}
func (m *GetBannerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBannerRequest.Merge(m, src)
}
func (m *GetBannerRequest) XXX_Size() int {
	return xxx_messageInfo_GetBannerRequest.Size(m)
}
func (m *GetBannerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBannerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBannerRequest proto.InternalMessageInfo

func (m *GetBannerRequest) GetBannerId() int32 {
	if m != nil {
		return m.BannerId
	}
	return 0
}

type GetBannerResponse struct {
	// The retrieved banner
	Banner               *Banner  `protobuf:"bytes,1,opt,name=banner,proto3" json:"banner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBannerResponse) Reset()         { *m = GetBannerResponse{} }
func (m *GetBannerResponse) String() string { return proto.CompactTextString(m) }
func (*GetBannerResponse) ProtoMessage()    {}
func (*GetBannerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_420fb4f4a183e532, []int{8}
}

func (m *GetBannerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBannerResponse.Unmarshal(m, b)
}
func (m *GetBannerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBannerResponse.Marshal(b, m, deterministic)
}
func (m *GetBannerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBannerResponse.Merge(m, src)
}
func (m *GetBannerResponse) XXX_Size() int {
	return xxx_messageInfo_GetBannerResponse.Size(m)
}
func (m *GetBannerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBannerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBannerResponse proto.InternalMessageInfo

func (m *GetBannerResponse) GetBanner() *Banner {
	if m != nil {
		return m.Banner
	}
	return nil
}

type ListBannersRequest struct {
	// Ids of the banners to list
	BannerIds            []int32  `protobuf:"varint,1,rep,packed,name=banner_ids,json=bannerIds,proto3" json:"banner_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBannersRequest) Reset()         { *m = ListBannersRequest{} }
func (m *ListBannersRequest) String() string { return proto.CompactTextString(m) }
func (*ListBannersRequest) ProtoMessage()    {}
func (*ListBannersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_420fb4f4a183e532, []int{9}
}

func (m *ListBannersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBannersRequest.Unmarshal(m, b)
}
func (m *ListBannersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBannersRequest.Marshal(b, m, deterministic)
}
func (m *ListBannersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBannersRequest.Merge(m, src)
}
func (m *ListBannersRequest) XXX_Size() int {
	return xxx_messageInfo_ListBannersRequest.Size(m)
}
func (m *ListBannersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBannersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBannersRequest proto.InternalMessageInfo

func (m *ListBannersRequest) GetBannerIds() []int32 {
	if m != nil {
		return m.BannerIds
	}
	return nil
}

type ListBannersResponse struct {
	// The banners
	Banners              []*Banner `protobuf:"bytes,1,rep,name=banners,proto3" json:"banners,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListBannersResponse) Reset()         { *m = ListBannersResponse{} }
func (m *ListBannersResponse) String() string { return proto.CompactTextString(m) }
func (*ListBannersResponse) ProtoMessage()    {}
func (*ListBannersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_420fb4f4a183e532, []int{10}
}

func (m *ListBannersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBannersResponse.Unmarshal(m, b)
}
func (m *ListBannersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBannersResponse.Marshal(b, m, deterministic)
}
func (m *ListBannersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBannersResponse.Merge(m, src)
}
func (m *ListBannersResponse) XXX_Size() int {
	return xxx_messageInfo_ListBannersResponse.Size(m)
}
func (m *ListBannersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBannersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBannersResponse proto.InternalMessageInfo

func (m *ListBannersResponse) GetBanners() []*Banner {
	if m != nil {
		return m.Banners
	}
	return nil
}

func init() {
	proto.RegisterEnum("github.go_sample_service.Banner_BannerType", Banner_BannerType_name, Banner_BannerType_value)
	proto.RegisterType((*Banner)(nil), "github.go_sample_service.Banner")
	proto.RegisterType((*AddBannerRequest)(nil), "github.go_sample_service.AddBannerRequest")
	proto.RegisterType((*AddBannerResponse)(nil), "github.go_sample_service.AddBannerResponse")
	proto.RegisterType((*DeleteBannerRequest)(nil), "github.go_sample_service.DeleteBannerRequest")
	proto.RegisterType((*DeleteBannerResponse)(nil), "github.go_sample_service.DeleteBannerResponse")
	proto.RegisterType((*UpdateBannerRequest)(nil), "github.go_sample_service.UpdateBannerRequest")
	proto.RegisterType((*UpdateBannerResponse)(nil), "github.go_sample_service.UpdateBannerResponse")
	proto.RegisterType((*GetBannerRequest)(nil), "github.go_sample_service.GetBannerRequest")
	proto.RegisterType((*GetBannerResponse)(nil), "github.go_sample_service.GetBannerResponse")
	proto.RegisterType((*ListBannersRequest)(nil), "github.go_sample_service.ListBannersRequest")
	proto.RegisterType((*ListBannersResponse)(nil), "github.go_sample_service.ListBannersResponse")
}

func init() {
	proto.RegisterFile("proto/banners_api.proto", fileDescriptor_420fb4f4a183e532)
}

var fileDescriptor_420fb4f4a183e532 = []byte{
	// 549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xcf, 0x6e, 0xda, 0x40,
	0x10, 0xc6, 0x6b, 0xfe, 0x39, 0x1e, 0xaa, 0x8a, 0x2c, 0x51, 0x63, 0x51, 0x45, 0xb5, 0x7c, 0x42,
	0x4d, 0x63, 0x24, 0x72, 0x69, 0x7b, 0x23, 0x6a, 0x55, 0x21, 0x11, 0x29, 0xb5, 0x52, 0x55, 0xea,
	0x05, 0x99, 0xec, 0xc4, 0x75, 0x05, 0xde, 0xed, 0xee, 0x52, 0x35, 0x4f, 0xd0, 0xf7, 0xe8, 0xeb,
	0xf5, 0x25, 0x22, 0xbc, 0x6b, 0x62, 0x08, 0x10, 0x10, 0x27, 0xe3, 0xf5, 0x7c, 0xdf, 0x7c, 0x33,
	0xfe, 0x19, 0x38, 0xe6, 0x82, 0x29, 0xd6, 0x19, 0x45, 0x69, 0x8a, 0x42, 0x0e, 0x23, 0x9e, 0x04,
	0xd9, 0x09, 0x71, 0xe3, 0x44, 0xfd, 0x98, 0x8e, 0x82, 0x98, 0x0d, 0x65, 0x34, 0xe1, 0x63, 0x1c,
	0x4a, 0x14, 0xbf, 0x93, 0x1b, 0x6c, 0xbd, 0x8e, 0x19, 0x8b, 0xc7, 0xd8, 0xc9, 0xea, 0x46, 0xd3,
	0xdb, 0x8e, 0x4a, 0x26, 0x28, 0x55, 0x34, 0xe1, 0x5a, 0xea, 0xff, 0x2f, 0x41, 0xed, 0x22, 0x33,
	0x24, 0xaf, 0xc0, 0xd1, 0xd6, 0xc3, 0x84, 0xba, 0x96, 0x67, 0xb5, 0xab, 0xe1, 0x81, 0x3e, 0xe8,
	0x53, 0x32, 0x80, 0xba, 0x79, 0xa8, 0xee, 0x38, 0xba, 0x25, 0xcf, 0x6a, 0xbf, 0xe8, 0x9e, 0x06,
	0xeb, 0x1a, 0x07, 0xda, 0xd3, 0x5c, 0xae, 0xef, 0x38, 0x86, 0x30, 0x9a, 0xff, 0x26, 0xef, 0x01,
	0xf0, 0x0f, 0x4f, 0x04, 0xca, 0x61, 0xa4, 0xdc, 0xb2, 0x67, 0xb5, 0xeb, 0xdd, 0x56, 0xa0, 0xb3,
	0x06, 0x79, 0xd6, 0xe0, 0x3a, 0xcf, 0x1a, 0x3a, 0xa6, 0xba, 0xa7, 0x66, 0xd2, 0x1b, 0x81, 0x91,
	0x42, 0x3a, 0x93, 0x56, 0x9e, 0x96, 0x9a, 0xea, 0x9e, 0x22, 0xc7, 0x60, 0x0b, 0xe4, 0x6c, 0x36,
	0x5e, 0x35, 0x1b, 0xaf, 0x36, 0xbb, 0xed, 0x53, 0x72, 0x62, 0x3c, 0x59, 0x36, 0x7a, 0x2d, 0x7b,
	0xe6, 0x98, 0x93, 0x3e, 0x25, 0x2e, 0xd8, 0x13, 0x94, 0x32, 0x8a, 0xd1, 0xb5, 0x3d, 0xab, 0xed,
	0x84, 0xf9, 0xad, 0x1f, 0x00, 0x3c, 0x4c, 0x48, 0x1c, 0xa8, 0x7e, 0x12, 0x82, 0x89, 0xc6, 0x33,
	0x72, 0x00, 0x95, 0x7e, 0x7a, 0xcb, 0x1a, 0x16, 0xa9, 0x83, 0xfd, 0x2d, 0x12, 0x69, 0x92, 0xc6,
	0x8d, 0x92, 0x3f, 0x80, 0x46, 0x8f, 0x52, 0x2d, 0x09, 0xf1, 0xd7, 0x14, 0xa5, 0x22, 0xef, 0xa0,
	0xa6, 0x37, 0x93, 0xed, 0xbc, 0xde, 0xf5, 0x9e, 0x5a, 0x6a, 0x68, 0xea, 0xfd, 0x4b, 0x38, 0x2c,
	0xb8, 0x49, 0xce, 0x52, 0x89, 0x7b, 0xd8, 0x75, 0xa1, 0xf9, 0x11, 0xc7, 0xa8, 0x70, 0x31, 0xdf,
	0x26, 0x2c, 0xfc, 0x97, 0x70, 0xb4, 0xa8, 0xd1, 0x29, 0xfc, 0xbf, 0x16, 0x34, 0xbf, 0x72, 0x1a,
	0xed, 0x62, 0xb6, 0x44, 0x45, 0x69, 0x17, 0x2a, 0x0a, 0xaf, 0xa8, 0xbc, 0xf8, 0x8a, 0xae, 0xe0,
	0x68, 0x31, 0xc8, 0xde, 0x7b, 0xea, 0x40, 0xe3, 0x33, 0xaa, 0x1d, 0x96, 0x74, 0x09, 0x87, 0x05,
	0xc1, 0xde, 0xfd, 0xcf, 0x81, 0x0c, 0x12, 0x69, 0xfc, 0x64, 0x9e, 0xe0, 0x04, 0x60, 0x9e, 0x40,
	0xba, 0x96, 0x57, 0x9e, 0x31, 0x9c, 0x47, 0x90, 0xfe, 0x17, 0x68, 0x2e, 0x88, 0x4c, 0x8a, 0x0f,
	0x60, 0x9b, 0xbf, 0x93, 0x4c, 0xb2, 0x4d, 0x8c, 0x5c, 0xd0, 0xfd, 0x57, 0xc9, 0xe9, 0x97, 0xbd,
	0xab, 0x3e, 0xa1, 0xe0, 0xcc, 0x69, 0x24, 0x6f, 0xd6, 0xdb, 0x2c, 0x7f, 0x00, 0xad, 0xd3, 0xad,
	0x6a, 0x4d, 0xe0, 0x09, 0x3c, 0x2f, 0x02, 0x47, 0xce, 0xd6, 0x8b, 0x57, 0xc0, 0xdc, 0x0a, 0xb6,
	0x2d, 0x7f, 0x68, 0x57, 0xa4, 0x67, 0x53, 0xbb, 0x15, 0xb8, 0x6f, 0x6a, 0xb7, 0x12, 0x4a, 0x0a,
	0xce, 0x9c, 0x94, 0x4d, 0x3b, 0x5c, 0xe6, 0x6f, 0xd3, 0x0e, 0x1f, 0xa3, 0xf7, 0x13, 0xea, 0x05,
	0x16, 0xc8, 0xdb, 0xf5, 0xda, 0xc7, 0x9c, 0xb5, 0xce, 0xb6, 0xac, 0xd6, 0xbd, 0x2e, 0xec, 0xef,
	0x55, 0xfd, 0xe5, 0xd6, 0xb2, 0xcb, 0xf9, 0x7d, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5a, 0xef, 0x8b,
	0x92, 0xc5, 0x06, 0x00, 0x00,
}
