name: licensed

on:
  # run on demand
  workflow_dispatch: 
  # run on a schedule
#  schedule: 
#    - cron: '*/5 * * * *' # e.g. every 5 minutes
    
jobs:
  licensed:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        licensed: [3.9.0, 3.9.1, 3.8.0, 3.7.5, 3.7.4, 3.7.3, 3.7.2, 3.7.1, 3.7.0, 3.6.0]
        node: [14.x, 16.x, 18.x]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-npm@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: jonabc/setup-licensed@8a9b5d622799ffaf33e456e3b5f43e10335c2857
        with:
          version: ${{ matrix.licensed }}
      - uses: jonabc/licensed-ci@d9a8780f100ce636a797d21bc351dd46d684e05c
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
