name: Verify cached license metadata

on:
  # run on pushes to the default branch
  push:
    branches:
      - main
  # run on all pull request events
  pull_request:
  # run on demand
  workflow_dispatch:

jobs:
  licensed:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # make sure git can access private repos
      # to pull packages during go commands
      - name: Configure git private repo access
        env:
          TOKEN: ${{ secrets.TEST_PAT }}
        run: |
          git config --global --add url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"

      # checkout the repo
      - uses: actions/checkout@v2
        with:
          # licensed-ci expects that the branch relating to the action run is available.
          # for pull_request events this checks out the PR merge ref, which does not point
          # at the head branch.  fetching all refs ensures that everything is available
          # for licensed-ci to run
          fetch-depth: 0

      # set up tooling
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - uses: jonabc/setup-licensed@v1
        with:
          version: 3.x

      # run licensed
      - uses: jonabc/licensed-ci@test-git-auth-in-url
        with:
          github_token: ${{ secrets.TEST_PAT }}
          # the "push" workflow updates license metadata files on the branch being examined.
          # e.g. when the action is run on main, changes are pushed to main

          # the "branch" workflow creates a new branch for license file updates.
          # e.g. when the action is run on main, changes are pushed to a new "main-licenses" branch

          # see https://github.com/jonabc/licensed-ci for more details
          workflow: push
          user_name: jonabc
          user_email: jonabc@github.com
        env:
          GOPRIVATE: "*github.com/github/*"
          GOPROXY: "direct"
