name: Verify cached license metadata for PR

on:
  push:
  # run on demand
  workflow_dispatch:

jobs:
  licensed:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # make sure git can access private repos
      # to pull packages during go commands
      - name: Configure git private repo access
        env:
          TOKEN: ${{ secrets.TEST_PAT }}
        run: |
          git config --global --add url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"

      # checkout the repo
      - uses: actions/checkout@v2

      # set up tooling
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - uses: jonabc/setup-licensed@v1
        with:
          version: 3.x

      - run: |
          git config --add http.https://github.com/.extraheader "foo: bar"
          git config --add http.extraheader "Authorization: basic 123"
          git config --add http.extraheader "foo: bar"

      # run licensed
      - uses: jonabc/licensed-ci@override-auth-extraheaders-on-push
        with:
          github_token: ${{ secrets.TEST_PAT }}
        env:
          GOPRIVATE: "*github.com/github/*"
          GOPROXY: "direct"
