name: Prompt for PR merged early reason 

on:
  pull_request:
    types: [ closed ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          // ignore PRs that were not merged
          console.log(context.payload);
          const pullRequest = context.payload.pull_request;
          if (!pullRequest.merged) {
            return;
          }

          const createdAt = new Date(pullRequest.created_at);
          const mergedAt = new Date(pullRequest.merged_at);
          const timeToMergeInSeconds = (mergedAt - createdAt) / 1000;
          
          const minimumTimeInSeconds = 60 * 60 * 24; // 1 day
          
          // ignore if the time to merge is greater than or equal to the minimum time
          if (timeToMergeInSeconds >= minimumTimeInSeconds) {
            return;
          }

          // leave a comment on the PR asking for a reason why the PR was merged
          // before the minimum time elapsed
          const comment = `:wave: @${pullRequest.merged_by}, this PR was merged faster than [expected](https://github.com/github/insights/blob/master/docs/how-we-work/authoring-issues-and-prs.md#pull-requests-should-be-open-for-a-minimum-of-24-hours)! If you haven't already, please leave a comment on this PR with any reasons why the PR was merged quickly so the team is aware.  Thanks :bow:!`;
          await github.issues.createComment({
            issue_number: pullRequest.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
